INSERT INTO `actividades` (`actividad`, `descripcion_actividad`) VALUES
('Resolución de problemas', ''),
('Búsqueda de información:', ''),
('usando la combinación de celdas posicionar vertical y horizontalmente texto y números', ''),
('canción', ''),
('Creación de un perfil profesional e invitar al docente en su red', NULL),
('Inscripción a 3 ofertas laborales como técnico en sistemas', NULL),
('Ejercicios prácticos de creación de carpetas', NULL),
('clasificación de componentes del computador', NULL),
('Elaboración de ejercicios de administración de documentos de texto plano', NULL),
('elaboración de guía de administración de documentos de texto', NULL),
('elaboración de una guía con los pasos de instalación', NULL),
('Creación de documentos y carpetas', NULL),
('Creación de una presentación de un tema especifico', NULL),
('preparación del contenido de una presentación', NULL),
('Grabación de cd', NULL),
('guías de estudio', NULL),
('elaboración de un horario', NULL),
('Teniendo en cuenta una hoja de cálculo electrónica posicionar nombre y apellidos de forma horizontal y vertical', NULL),
('Desarrollo de ejercicio de nómina con apoyo financiado', NULL),
('desarrollo de ejercicio de nómina con apoyo financiado con uso de operaciones matemáticas básicas', NULL),
('Producir un Certificado para los compañeros mediante combinación de correspondencia', NULL),
('Diseño de una calculadora básica', NULL),
('elaboración de una guía paso a paso para desarrollar una calculadora', NULL),
('Realizar el diseño de base de datos de un proyecto brindado por el docente', NULL),
('Transcripción y formato de párrafo', NULL),
('transcripción y formato de párrafo', NULL),
('Elaboración de publicidad animada', NULL),
('elaboración de publicidad animada', NULL),
('Creación de un formulario de notas', NULL),
('Creación de un módulo de sistema seguro', NULL),
('Elaboración de página web', NULL),
('maquetación de página web en papel', NULL),
('animación publicitaria', NULL),
('Transcripción de audios', NULL),
('transcripción de audios', NULL),
('Elaboración de un póster', NULL),
('elaboración de un póster', NULL),
('Elaboración de logo para empresa privada', NULL),
('Elaboración de identidad corporativa', NULL),
('elaboración de identidad corporativa', NULL),
('instalación de un proyecto web', NULL),
('Crear una presentación del producto o servicio empresarial', NULL),
('Realizar una aplicación que permita el control de ingreso de personas', NULL),
('diseñar el prototipo de una aplicación que permita el control de ingreso de personas', NULL),
('Crear un proceso de administración de personal usando salesforce', NULL),
('Sustentación del plugin', NULL),
('Desarrollar un proyecto de base de datos desde su diseño', NULL),
('Administración de personal con macros', NULL),
('descripción de pasos para grabar macros', NULL),
('Nómina', NULL),
('Desarrollar un proyecto de analítica de datos', NULL),
('Creación de un formulario fundamentado en un proyecto', NULL),
('diseñar un formulario fundamentado en un proyecto', NULL),
('Realizar el montaje de un punto de red', NULL),
('Repetición de una red cercana', NULL),
('elaboración de guía sobre repetición de una red cercana', NULL),
('Validar un sitio web y una dirección mac', NULL),
('Desarrollar un semáforo usando la instrucción mientras y condicionales', NULL),
('Diseño de un ejemplo de base de datos', NULL),
('Diseño de una base de datos de un problema en específico', NULL),
('elaborar un proyecto y consultas de base que permitan presentar estadísticas', NULL),
('Realizar el proceso de creación y consulta de una base de datos mysql teniendo en cuenta una problemática', NULL),
('realizar un paso a paso del proceso de creación de base de datos y realizar consultas sql en cuaderno', NULL),
('Desarrollar la temática con un módulo diferente al observado en clase', NULL),
('realizar una fusión de impresión con publicidad', NULL),
('realizar los pasos de una fusión de impresión con publicidad', NULL),
('Calcular el rango superior e inferior de los distintos dispositivos para el 75% de los días', NULL),
('Realizar un análisis de la información de facebook', NULL),
('realizar un laboración de una guía con los pasos de instalación conectarlo a power bi y generar visualización junto análisis de sentimiento', NULL),
('En binas uno de los compañeros tendrá que ensamblar el computador y otro tendrá que desamblar el ordenador', NULL),
('Realizar instalación de sistemas operativos windows y linux', NULL),
('Replicación de un sitio web usando power point', NULL),
('replicación de un sitio web usando el cuaderno', NULL),
('Repetir el proceso de instalación de wordpress', NULL),
('describir paso a paso el proceso de instalación', NULL),
('Creación de un proyecto web', NULL),
('descripción de la creación de un sitio web', NULL);