# SCRIPT DE RESTAURACION PARA: prompt
$RUTA_RESPALDO = "D:\xampp\htdocs\guagua\reportes\bd\automatico\prompt"
$XAMPP_MYSQL_PATH = "D:\xampp\mysql"
$MYSQL_BIN_PATH = Join-Path $XAMPP_MYSQL_PATH "bin/mysql.exe"
$USUARIO = "root"
$MYSQL_HOST = "localhost"
$PUERTO = "7000"
$BASE_DATOS = "prompt"
# ... (el resto del script de restauraciÃ³n es idÃ©ntico y se rellena con las variables correctas)
$MOSTRAR_MENSAJES = $true; function Mostrar-Mensaje { param([string]$m) if ($MOSTRAR_MENSAJES) { Write-Host $m -ForegroundColor Cyan } }; function Mostrar-Error { param([string]$m) Write-Host "ERROR: $m" -ForegroundColor Red; Add-Content "$RUTA_RESPALDO/import_error.log" "[$(Get-FechaAmigable)] ERROR: $m"; Read-Host "Presiona Enter para cerrar."; exit 1 }; function Get-FechaAmigable { Get-Date -Format "dd/MM/yyyy HH:mm:ss" }; Mostrar-Mensaje "--- INICIO DEL SCRIPT DE RESTAURACION PARA 'prompt' [$(Get-FechaAmigable)] ---";$dataDir = Join-Path $XAMPP_MYSQL_PATH "data"; $backupDirRest = Join-Path $XAMPP_MYSQL_PATH "backup"; if (-Not (Test-Path $backupDirRest)) { Mostrar-Error "La carpeta '$backupDirRest' no existe." }; if (Test-Path $dataDir) { $fechaUnica = Get-Date -Format "yyyyMMdd_HHmmss"; $nuevoNombreData = "data_respaldo_$fechaUnica"; $nuevoPathData = Join-Path $XAMPP_MYSQL_PATH $nuevoNombreData; Mostrar-Mensaje "Renombrando '$dataDir' a '$nuevoPathData'..."; try { Rename-Item -Path $dataDir -NewName $nuevoNombreData -ErrorAction Stop } catch { Mostrar-Error "No se pudo renombrar '$dataDir'. Error: $_.Exception.Message" } } else { Mostrar-Mensaje "La carpeta 'data' no existe." }; Mostrar-Mensaje "Copiando '$backupDirRest' a 'data'..."; try { Copy-Item -Path $backupDirRest -Destination $dataDir -Recurse -Force -ErrorAction Stop } catch { Mostrar-Error "No se pudo copiar. Error: $_.Exception.Message" }; if (-Not (Test-Path $MYSQL_BIN_PATH)) { Mostrar-Error "mysql.exe no encontrado." };$archivoSQL = Get-ChildItem $RUTA_RESPALDO -Filter *.sql | Where-Object Length -gt 0 | Sort-Object CreationTime -Descending | Select-Object -First 1; if (-Not $archivoSQL) { Mostrar-Error "No se encontro .sql valido." }; Mostrar-Mensaje "Archivo: $($archivoSQL.Name)"; & $MYSQL_BIN_PATH --user=$USUARIO --host=$MYSQL_HOST --port=$PUERTO -e "CREATE DATABASE IF NOT EXISTS $BASE_DATOS CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;"; if ($LASTEXITCODE -ne 0) { Mostrar-Error "No se pudo crear la BD." }; try { Get-Content -Path $archivoSQL.FullName -Raw | & $MYSQL_BIN_PATH --user=$USUARIO --host=$MYSQL_HOST --port=$PUERTO --default-character-set=utf8mb4 --database=$BASE_DATOS } catch { Mostrar-Error "Fallo la importacion. Error: $_.Exception.Message" }; Mostrar-Mensaje "--- PROCESO COMPLETADO ---"; Read-Host "Presiona Enter."
